User verification
OfficialTomJ/IoTBay pull request #31
Opened 2024-04-30 16:29 UTC by Adam2221114

2024-05-01 09:26 UTC, OfficialTomJ commented on server/controllers/userController.js
> +            eventType: 'account_created',
Indentation issue

2024-05-01 09:26 UTC, OfficialTomJ commented on server/controllers/userController.js
> +    try {
Indentation issue

2024-05-01 09:27 UTC, OfficialTomJ commented on server/controllers/userController.js
> +    try {
Indention issue

2024-05-01 09:29 UTC, OfficialTomJ commented on server/models/Payment.js
Rebase file

2024-05-01 09:30 UTC, OfficialTomJ requested changes
Rebase Payment.js and fix indentation issues

2024-05-09 06:00 UTC, OfficialTomJ requested changes
When testing the features on the branch, the server crashes as Nodemailer is not installed as a dependency. This is due to you manually uploading files (which I've told you to not do multiple times) and not having the package.json tracked in the commit history.

Please commit to branch properly and track ALL file changes to associated src files and dependency trackers. If you are adding new packages, you will have to track changes in the package.json and package-lock.json files.

<img width="558" alt="Screenshot 2024-05-09 at 3 57 57 pm" src="https://github.com/OfficialTomJ/IoTBay/assets/8527295/74dd8c78-ba41-4c31-a8c1-d3a8e7387f5c">

2024-05-09 06:33 UTC, OfficialTomJ requested changes
package.json and package-lock.json files not included

2024-05-09 15:46 UTC, Adam2221114 commented
Fixed

2024-05-10 04:26 UTC, OfficialTomJ approved these changes

2024-05-10 04:27 UTC, merged